#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
wal -i ~/Pictures/Wallpapers/Wallpaper.png
wal -R
nitrogen --restore --set-scaled &
polybar &
dunst &

bspc monitor -d       

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true

bspc config border_width         3
bspc config window_gap          15 

bspc config split_ratio          0.60
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Blender desktop='^3' follow=on
bcps rule -a "spotify" desktop='^4' 
bspc rule -a Steam desktop='^5'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
