# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  
  boot = {
    blacklistedKernelModules = ["amdgpu"];                                                # Blacklist amdgpu.
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
      prepend = [ "${../dotfiles/patched_cirrus_acpi.cpio}" ];                            # Correct DSDT for Cirrus amplifier.
    };
    kernelModules = [ "kvm-amd" ];
    swraid.enable = false; 
    extraModulePackages = [ ];
        kernelPatches = [ 
      {
        name = "Realtek";                                                                 # Add patch for Cirrus amplifier.
        patch = ../dotfiles/scar.patch;
      }
      {
        name = "Foxconn Bluetooth";                                                       # Add patch for bluetooth support.
        patch = ../dotfiles/bt.patch;
      }
    ];
  };

  fileSystems = {
    "/boot" = { 
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    }; 

    "/" = { 
      device = "/dev/disk/by-label/SYSTEM";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

    "/home" = { 
      device = "/dev/disk/by-label/HOME";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ]; 
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking = {
    hostName = "scar";
    useDHCP = lib.mkDefault true;
  };

  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs = {
    overlays = [
      (self: super: {
        blender = super.blender.override {
          cudaSupport = true;                   # Add CUDA support for blender
        };
     })
    ];
  };

  hardware= {
   cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
   opengl.extraPackages = with pkgs; [          # Add VDPAU support.
      vaapiVdpau
      libvdpau-va-gl
   ];
  };
  
  services = {
    fstrim = {
      enable = true;                            # Enable weekly SSD trim.
      interval = "weekly";
    };
#    tlp.enable = true;                          # Use TLP daemon for power management.
    upower.enable = true;                       # Use upower for applications power management via D-Bus.
    xserver= {
      videoDrivers = ["nvidia"];                # Use nVidia proprietary driver.
      dpi = 108;                                # DPI correction.
      libinput = {
        enable = true;                          # Enable touchpad support.
        touchpad.disableWhileTyping = true;     # Disable touchpad while typing.
      };
    };
  };
}
