# hosts/<hostname>/configuration.nix
{ stateVersion, ... }:

{
  ##########################################
  ## Host Configuration Entry Point
  ##########################################
  ##
  ## This file defines the system configuration for this specific host.
  ## It stitches together shared modules (from ../../modules/) that
  ## handle each subsystem—like boot, users, networking, Hyprland, etc.
  ##
  ## The structure allows reuse across multiple machines while
  ## maintaining host-specific overrides here if needed.
  ##########################################

  imports = [
    ##########################################
    ## Core System Modules
    ##########################################
    ./hardware.nix               # Auto-generated by nixos-generate-config
    ../../modules/boot.nix       # Bootloader setup (systemd-boot, EFI)
    ../../modules/users.nix      # User & group management
    ../../modules/network.nix    # NetworkManager, firewall, and utilities
    ../../modules/nix.nix        # Nix daemon, flakes, and GC settings
    ../../modules/locale.nix     # Locale, timezone, and keyboard layout

    ##########################################
    ## Desktop Environment & UX
    ##########################################
    ../../modules/hyprland.nix   # Hyprland compositor (Wayland)
    ../../modules/portals.nix    # XDG desktop portals (for Wayland apps)
    ../../modules/multimedia.nix # Audio/Video stack (PipeWire, codecs)

    ##########################################
    ## System Services
    ##########################################
    ../../modules/services.nix   # SSH, daemons, power mgmt, etc.

    ##########################################
    ## Gaming Stack
    ##########################################
    ../../modules/games.nix      # Steam, Lutris, Heroic, Wine, MangoHud, etc.
  ];

  ##########################################
  ## Host-Level Overrides (optional)
  ##########################################
  ##
  ## Add host-specific settings below if this machine differs
  ## from others (e.g., hostname, special hardware options,
  ## custom fonts, display layouts, etc.)
  ##
  ## Example:
  ##
  ## networking.hostName = "zephyrus";
  ## services.fstrim.enable = true;
  ## hardware.cpu.amd.updateMicrocode = true;
  ##########################################

  ##########################################
  ## System State Version
  ##########################################
  ##
  ## Ensures reproducibility across upgrades. Should match
  ## the `stateVersion` value passed from flake.nix.
  ##
  ## When upgrading NixOS, bump this *only* when you are ready
  ## to adopt new defaults or behaviors introduced in that release.
  ##########################################
  system.stateVersion = stateVersion;

  ##########################################
  ## Summary of Imported Features
  ##########################################
  ##
  ## ✅ Bootloader: systemd-boot (UEFI)
  ## ✅ Network: NetworkManager + firewall
  ## ✅ Nix: flakes + auto store optimization + GC
  ## ✅ Locale: timezone, keymap, language
  ## ✅ Desktop: Hyprland compositor (Wayland)
  ## ✅ Portals: Wayland app compatibility
  ## ✅ Multimedia: PipeWire, codecs, VAAPI
  ## ✅ Services: SSH, daemons, optional power mgmt
  ## ✅ Games: Steam, Lutris, Heroic, Proton, MangoHud, Wine
  ## ✅ Users: declarative normal users + groups
  ##########################################
}

