# hosts/<hostname>/configuration.nix
{ stateVersion, ... }:

{
  ##########################################
  ## Host Configuration Entry Point
  ##########################################
  ##
  ## This file ties together all module imports for a given host.
  ## Each imported file configures a specific subsystem (boot, users,
  ## networking, Hyprland, etc.). The overall structure ensures that
  ## each host can reuse shared modules with minimal duplication.
  ##
  ## Parameters:
  ## - `stateVersion`: passed from flake.nix for consistent system evolution.
  ##########################################

  imports = [
    ##########################################
    ## Core system modules
    ##########################################
    ./hardware.nix              # Auto-generated by nixos-generate-config
    ../../modules/boot.nix      # Bootloader (systemd-boot, EFI)
    ../../modules/users.nix     # User and group definitions
    ../../modules/network.nix   # Networking + firewall + utilities
    ../../modules/nix.nix       # Nix daemon and flake configuration
    ../../modules/locale.nix    # Locale, time, and keyboard settings

    ##########################################
    ## Desktop and environment
    ##########################################
    ../../modules/hyprland.nix  # Hyprland compositor (Wayland)
    ../../modules/portals.nix   # XDG portals (for Wayland apps)
    ../../modules/multimedia.nix# Audio/Video stack (PipeWire, codecs, etc.)

    ##########################################
    ## Services
    ##########################################
    ../../modules/services.nix  # SSH, system services, daemons
  ];

  ##########################################
  ## System State Version
  ##########################################
  ## Ensures reproducibility across upgrades.
  ## Match this with your flake `stateVersion` variable.
  ##########################################
  system.stateVersion = stateVersion;
}

