# hosts/zephyrus/configuration.nix
# This is the entry point for host-specific settings.
# It imports shared modules from ../../modules and applies
# small per-machine overrides (hostname, trims, etc.).
{ stateVersion, lib, hostName, ... }:

{
  ##########################################
  ## Host Configuration Entry Point
  ##########################################

  imports = [
    # Hardware profile generated by `nixos-generate-config`.
    # Contains disk layout, filesystems, GPU drivers, etc.
    ./hardware-configuration.nix

    ##########################################
    ## Core System Modules
    ##########################################
    ../../modules/boot.nix     # UEFI/systemd-boot, kernel params, quiet boot
    ../../modules/users.nix    # Users/groups, sudo, shells
    ../../modules/network.nix  # NetworkManager, firewall, hostname helpers
    ../../modules/nix.nix      # Nix daemon, flakes, GC/optimizations
    ../../modules/sysenv.nix   # Locale/time/XKB, core CLI tools, env vars

    ##########################################
    ## Desktop Environment & UX
    ##########################################
    ../../modules/hyprland.nix   # Hyprland WM/compositor on Wayland
    ../../modules/portals.nix    # XDG portals for screen share, file pickers, etc.
    ../../modules/multimedia.nix # PipeWire/ALSA, codecs, VAAPI/Vulkan bits

    ##########################################
    ## System Services
    ##########################################
    ../../modules/services.nix   # SSH, power mgmt, timers/daemons, misc services

    ##########################################
    ## Gaming Stack
    ##########################################
    ../../modules/games.nix      # Steam/Lutris/Heroic, Proton, MangoHud, Wine
  ];

  ##########################################
  ## Host-Level Overrides (per-machine)
  ##########################################
  # Hostname sourced from the flake via specialArgs; this avoids hardcoding.
  networking.hostName = lib.mkDefault hostName;

  # Enable weekly SSD TRIM (safe for most modern SSDs).
  services.fstrim.enable = lib.mkDefault true;

  # (Pick the correct microcode line for your CPU vendor; keep one enabled.)
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  # hardware.cpu.amd.updateMicrocode   = lib.mkDefault true;

  # (Optional) Compressed RAM swap—nice for laptops with limited RAM.
  # zramSwap = { enable = lib.mkDefault true; memoryPercent = lib.mkDefault 25; };

  # (Optional) Enable Bluetooth by default if this machine needs it.
  # hardware.bluetooth.enable = lib.mkDefault true;

  ##########################################
  ## System State Version
  ##########################################
  # Locks in behavior compatible with the NixOS release you initially deployed.
  # Bump only when you intentionally adopt new defaults during an upgrade.
  system.stateVersion = stateVersion;
}

